--- 
executors:
  my-executor:
    docker:
      - image: "circleci/golang:1.12"
    working_directory: /go/sample-repo
    
jobs: 
  checkout_code:
    executor: my-executor
    steps:
      - checkout:
          post:
            - |
                if [[ -n "${CIRCLE_PR_NUMBER}" ]]
                then
                    # Update PR refs for testing.
                    FETCH_REFS="+${CIRCLE_PR_BASE_BRANCH}:${CIRCLE_PR_BASE_BRANCH}"
                    FETCH_REFS="${FETCH_REFS} +refs/pull/${CIRCLE_PR_NUMBER}/head:pr/${CIRCLE_PR_NUMBER}/head"
                    FETCH_REFS="${FETCH_REFS} +refs/pull/${CIRCLE_PR_NUMBER}/merge:pr/${CIRCLE_PR_NUMBER}/merge"

                    # Retrieve the refs
                    git fetch -u origin ${FETCH_REFS}

                    # Checkout PR merge ref.
                    git checkout -qf "pr/${CIRCLE_PR_NUMBER}/merge"

                    # Test for merge conflicts.
                    git branch --merged | grep ${CIRCLE_PR_BASE_BRANCH} > /dev/null
                    git branch --merged | grep "pr/${CIRCLE_PR_NUMBER}/head" > /dev/null
                fi
      -
        run:
          command: |
            go mod download
            go mod vendor
            go mod tidy
          name: "Build Dependencies"

      - persist_to_workspace:
          root: /go/sample-repo
          paths:
            - .
      - 
        save_cache: 
          key: "go-mod-v4-{{ checksum \"go.sum\" }}"
          paths: 
            - /go/pkg/mod

  build: 
    executor: my-executor
    steps:
      - attach_workspace:
          at: /go/sample-repo 
      - 
        restore_cache: 
          keys: 
            - "go-mod-v4-{{ checksum \"go.sum\" }}"
           
      - run:
          name: "Make coverage"
          command: |
            mkdir -p coverage/html
            go test -timeout 2m -cover -coverprofile=coverage/coverage.out -v ./... || (echo "Coverage tests failed")
            go tool cover -html=coverage/coverage.out -o coverage/html/main.html
            echo "Generated coverage/html/main.html"
            sed -i "s/sample/generated/g" sample-text
      - store_artifacts:
          path: coverage

      - 
        save_cache: 
          key: "go-mod-v4-{{ checksum \"go.sum\" }}"
          paths: 
            - /go/pkg/mod
    
  echo:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /go/sample-repo 
      - run:
          name: "Make coverage"
          command: |
            cat sample-text
    
version: 2.1
workflows: 
  build-workflow: 
    jobs: 
      - checkout_code
      - build:
          requires:
            - checkout_code
      - echo:
          requires:
            - build

